### ISSUE TITLE
Running frappuccino with napari fails

### ISSUE THREAD

**Issue by andy-sweet** [Carreau/frappuccino#7]
When I try to run frappuccino with napari, I get the following error:

```
(napari-dev) ➜  napari git:(main) frappuccino napari --save ~/temp/napari.json                        
Traceback (most recent call last):
  File "/Users/asweet/software/miniconda3/envs/napari-dev/bin/frappuccino", line 8, in <module>
    sys.exit(main())
  File "/Users/asweet/software/miniconda3/envs/napari-dev/lib/python3.9/site-packages/frappuccino/__init__.py", line 378, in main
    skipped, tree_visitor = visit_modules(rootname, options.modules)
  File "/Users/asweet/software/miniconda3/envs/napari-dev/lib/python3.9/site-packages/frappuccino/__init__.py", line 224, in visit_modules
    tree_visitor.visit(module)
  File "/Users/asweet/software/miniconda3/envs/napari-dev/lib/python3.9/site-packages/frappuccino/visitor.py", line 172, in visit
    visited_hash = visitor(node)
  File "/Users/asweet/software/miniconda3/envs/napari-dev/lib/python3.9/site-packages/frappuccino/visitor.py", line 330, in visit_module
    self.visit(item)
  File "/Users/asweet/software/miniconda3/envs/napari-dev/lib/python3.9/site-packages/frappuccino/visitor.py", line 172, in visit
    visited_hash = visitor(node)
  File "/Users/asweet/software/miniconda3/envs/napari-dev/lib/python3.9/site-packages/frappuccino/visitor.py", line 330, in visit_module
    self.visit(item)
  File "/Users/asweet/software/miniconda3/envs/napari-dev/lib/python3.9/site-packages/frappuccino/visitor.py", line 172, in visit
    visited_hash = visitor(node)
  File "/Users/asweet/software/miniconda3/envs/napari-dev/lib/python3.9/site-packages/frappuccino/visitor.py", line 311, in visit_module
    if key == item.__module__+'.'+item.__name__ :
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

This is at [c3e3c12611f4e118010d94ddcbb5f9da93093bd4 on napari](https://github.com/napari/napari/tree/c3e3c12611f4e118010d94ddcbb5f9da93093bd4) and with frappuccino 0.0.8. See [my conda environment for more details](https://gist.github.com/andy-sweet/b9201847976e402851d993117d28d451).

**Comment by Carreau** [comment]
You may want to try https://pypi.org/project/griffe/ that try to do similar things but is more active.
